import { BodyText } from 'components/Text'
import { Suspense } from 'react'
import { useSnapshot } from 'valtio'
import ContractListContainer from 'components/proofs/ContractListContainer'
import Proof from 'components/proofs/Proof'
import ProofStore from 'stores/ProofStore'

function ContractList() {
  const { proofsCompleted } = useSnapshot(ProofStore)

  return (
    <>
      {!!proofsCompleted?.length && (
        <ContractListContainer>
          {Array.from(proofsCompleted)
            .sort((a, b) => (a.account === b.account ? 0 : -1))
            .map((proof) => (
              <Proof
                proof={proof}
                contractAddress={proof.contract}
                key={`${proof.contract}-${proof.account}`}
              />
            ))}
        </ContractListContainer>
      )}
    </>
  )
}

export default function () {
  return (
    <Suspense
      fallback={<BodyText>Fetching proofs generated by you...</BodyText>}
    >
      <ContractList />
    </Suspense>
  )
}
