import { BodyText } from 'components/Text'
import { Suspense } from 'react'
import { useSnapshot } from 'valtio'
import Complete from 'icons/Complete'
import ContractListContainer from 'components/ContractListContainer'
import ContractName from 'components/ContractName'
import ProofLine from 'components/ProofLine'
import ProofStore from 'stores/ProofStore'
import WalletStore from 'stores/WalletStore'
import classnames, {
  alignItems,
  display,
  flexDirection,
  fontFamily,
  fontWeight,
  lineHeight,
  space,
  textColor,
} from 'classnames/tailwind'

const ProofText = classnames(
  display('flex'),
  flexDirection('flex-row'),
  space('space-x-2'),
  alignItems('items-center'),
  fontWeight('font-bold'),
  textColor('text-yellow'),
  fontFamily('font-primary'),
  lineHeight('leading-5')
)

function ContractList() {
  const { account } = useSnapshot(WalletStore)
  const { proofsCompleted } = useSnapshot(ProofStore)

  return (
    <>
      {!!proofsCompleted?.length && (
        <ContractListContainer>
          {proofsCompleted.map((proof) => (
            <ProofLine>
              <ContractName address={proof.contract} />
              <div className={ProofText}>
                <span>
                  Proof {proof.account === account ? 'made' : 'saved'}
                </span>
                <Complete color="yellow" />
              </div>
            </ProofLine>
          ))}
        </ContractListContainer>
      )}
    </>
  )
}

export default function ListOfReadyZKProofs() {
  return (
    <Suspense
      fallback={
        <BodyText size="base">
          Fetching ready proofs generated by you...
        </BodyText>
      }
    >
      <ContractList />
    </Suspense>
  )
}
