name: Build and lint code
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  build-and-lint-code:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: '--max_old_space_size=4096'
    steps:
      - uses: Borodutch/build-and-lint-code@v1.0.3
